### ISSUE TITLE
Relative path

### ISSUE THREAD

**Issue by ShayBox** [kalinda99/ARepoBuilder#1]
The script currently uses a hard coded /home/kalinda/ARepoBuilder instead of relative path

The ABS variable in `arepobuilder` doesn't use the one in `includes.sh`
`arepobuilder` doesn't have `.sh`
this lets you put things other than numbers, and also says dorrect
![image](https://user-images.githubusercontent.com/9505196/74705617-7f64e980-51e2-11ea-80eb-e14532a57897.png)

it clones each individual dependency and compiles them... Please use pacman packages if available, that adds so much more to building, about 20 days in `dolphin-emu-git`s case

**Comment by kalinda99** [comment]
Hello,

Thanks for the feedback! Today's batch of commits fixes all the issues you mentioned except the dependency one.

The idea behind that is that it uses `pacman -Ss` to search the repos for packages matching depends and makedepends from the PKGBUILD file. It is only supposed to clone and build them if they aren't in the repos but are in the AUR. It seems to work a lot of the time but sometimes it clones packages that are already in the repos and I'm honestly not sure why or how to fix it. I've seen it clone packages in the official Arch repos that don't even seem to exist in the AUR!

There's probably a better way to do this, I'm just not sure what it is yet. I am open to suggestions.

Thanks!
